name: Deploy Photo Share App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # =====================================================
  # BACKEND BUILD
  # =====================================================
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/


  # =====================================================
  # BACKEND DEPLOY
  # =====================================================
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F81D25B94B62447198DDE3C669060325 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B82C527FC8B849ABAE225DEC703D6C05 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F2ADEB11AB5240C18B671C8BF622B77B }}

      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'photo-share-api'
          slot-name: 'Production'


  # =====================================================
  # FRONTEND DEPLOY
  # =====================================================
    deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F81D25B94B62447198DDE3C669060325 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B82C527FC8B849ABAE225DEC703D6C05 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F2ADEB11AB5240C18B671C8BF622B77B }}

      - name: Upload frontend to Azure Storage Static Website
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name photostorageacctt \
              --destination '$web' \
              --source . \
              --overwrite true \
              --account-key "${{ secrets.AZURE_STORAGE_KEY }}" \
              --pattern "*.html"

            az storage blob upload-batch \
              --account-name photostorageacctt \
              --destination '$web' \
              --source . \
              --overwrite true \
              --account-key "${{ secrets.AZURE_STORAGE_KEY }}" \
              --pattern "*.css"

            az storage blob upload-batch \
              --account-name photostorageacctt \
              --destination '$web' \
              --source . \
              --overwrite true \
              --account-key "${{ secrets.AZURE_STORAGE_KEY }}" \
              --pattern "*.js"
